HUPO-PSI/psi-ms-CV

psi-ms.obo

Add missing Term headers

---

psi-ms.obo

Changed the value-type of MS:1000747 and MS:1002435 from date to dateTime to be able to include a time component and remain valid.

Changed the value-type of MS:1000747 and MS:1002435

---

psi-ms.obo

@jshofstahl  would you review this?

Add Exploris 240 and 120

---

psi-ms.obo

Fix formatting of def of MS:1003092

---

psi-ms.obo

As proposed in Peak interpretation format - Peptides:
https://docs.google.com/document/d/1yEUNG4Ump6vnbMDs4iV4s3XISflmOkRAyqUuutcCG2w

add 5 ion interpretation format terms

---

psi-ms.obo

Some scores and terms for PatternLab software (http://www.patternlabforproteomics.org/)

PatternLab information

---

psi-ms.obo

Does this look good @jshofstahl @edeutsch ?

Add Orbitrap ID-X

---

psi-ms.obo

@timosachsenberg @julianus new term  `OpenMS: ConsesusID PEP` created

OpenMS added score

---

psi-ms.obo

Updated and new ion mobility and other related terms for mzML

Updated and new terms for ion mobility

---

psi-ms.obo

We (PSI-QC working group) would like to add mzQC as a file format term in the PSI-MS-CV

add mzQC format to the CV

---

psi-ms.obo
scripts/find_next_available_number.py

Closes #72 
Also added a handy script to find gaps in accession number space.

Add Tryp-N #72

---

.github/ISSUE_TEMPLATE/new_term.yaml
README.md

This is a first pass at addressing #51 in the README.
I also tried adding an issue template, but it seems like GitHub has changed the format for these recently.

Add README text and issue template for new term request process

---

psi-ms.obo

Similar to #75, additional tools for QC metric calculation.

Add QuaMeter and iMonDB software

---

psi-ms.obo

Add Bruker instruments and PeakForest

---

psi-ms.obo

updating MS:4000063 and other terms with dbxref and synonyms and comment

---

psi-ms.obo

Please see the term description in #111

adding new qc terms in resp. to #111

---

psi-ms.obo

Please see the term description in #110

 adding new qc terms in resp to #110

---

psi-ms.obo

Add missing NCIT terms

---

psi-ms.obo

Add term for Casanovo

---

psi-ms.obo

Add electron activated dissociation and SCIEX ZenoTOF

---

psi-ms.obo

* acquisition metrics
* some id-based metrics

New batch of QC metric terms

---

.gitignore
psi-ms.obo

Lipidomics terms

---

psi-ms.obo

Closes #173 
@oliver-bernhardt, is there any other information to include? I put the DOI for the referenced paper in the definition reference.

Add Spectronaut software term

---

psi-ms.obo

Closes #171 
Closes #170 
@colin-combe did I miss anything from the set of issues?

Add regex changes for modification localization and crosslinking FDR

---

psi-ms.obo

Followupbatchofqcmetrics

---

psi-ms.obo
scripts/find_next_available_number.py

This PR introduces the new terms for the mzIdentML extension for crosslinking.
@colin-combe
@lutzfischer

mzIdentML Crosslinking Terms

---

psi-ms.obo

Add FLASHDeconv term

---

psi-ms.obo

Add fixes from 2/28/23 crosslinking call

---

psi-ms.obo

Thermo Ascend

---

psi-ms.obo

Closes #188 #187 #184 #186 and adds the batch of Tide terms from mailing list.
@colin-combe I repeat your edit here so that there is a single version number change for this batch as the release automation isn't fixed yet.
@bittremieux I've added your two iRT terms with the value type specified, assuming that the JSON format dictates they'll be deserialized appropriately as floats.
@mwalzer ANN-SoLo term added using the full description listed.

Add batch of terms

---

psi-ms.obo

Add SelexION compensation voltage

---

psi-ms.obo

I need this for my @OpenChrom / ChemClipse mzML converter.
References: [Wikidata](https://www.wikidata.org/wiki/Q72825661)

Added Open Chromatography Binary (*.ocb)

---

.github/workflows/merge-queue.yml
psi-ms.obo

Add Thermo Orbitrap Astral

---

psi-ms.obo

New Waters and Bruker Instruments

---

psi-ms.obo

Crosslinking extension document version

---

psi-ms.obo

Add mzTab-M term

---

psi-ms.obo

Add new term SelexION separation voltage based on documentation here:
https://sciex.com/content/dam/SCIEX/pdf/tech-notes/all/SelexION-Technology-Solution-to-Selectivity-Challenges.pdf

Add SelexION separation voltage

---

psi-ms.obo

Remove redundant synonyms from software terms.

Remove redundant synonyms 

---

psi-ms.obo

Fix inconsistent QC metrics

---

psi-ms.obo

Hi,
I would like to add a new CV term for mzRecal. The PR should have all the info, the CV number still needs to be filled in though.
Please let me know if this is sufficient.
Rob

Add CV term for mzRecal software

---

psi-ms.obo

As discussed during the spring meeting.

De novo database format work around

---

psi-ms.owl

This automated PR updates the OWL file corresponding to the OBO file

Update OWL file

---

psi-ms.obo

also added dependency NCIT terms

add terms from #242 and #243

---

psi-ms.obo

Make the ::P|C fragment optional

---

psi-ms.obo

Fix the parent comment in MS:1003303

---

psi-ms.obo

This patch should fix #292 if the problem with imports being OBO files is the root cause.

Modify obo imports

---

psi-ms.obo

Closes #290
@pete-reay-waters is this sufficient detail?

Add Waters Xevo MRT

---

psi-ms.obo

Harmonize fraction as value concept

---

psi-ms.obo

rename MZmine to mzmine

---

psi-ms.obo

I would like to suggest these additions to the psi-ms.obo to support results from Kojak. Please double-check that I've made all the appropriate relationships and syntax, as I used a text editor to make my changes...

Updated psi-ms.obo to include the Kojak algorithm and its results.

---

psi-ms.obo

add Mobilion terms

---

.github/workflows/validate-owl.yaml
psi-ms.obo

Andromeda delta score added as requested in #356

Andromeda: delta score

---

psi-ms.obo

Closes #369 
@pete-reay-waters

Add `Waters DATA Convert` software

---

psi-ms.obo

Added terms for recent instrument and software releases. Update the def for MS:1000121 to be less verbose and similar to other instrument model defs.

Addition of Sciex instruments and software terms

---

psi-ms.obo

Add QC metrics

---

psi-ms.obo

This PR adds the metrics announced in #380 
@edeutsch @mobiusklein @bittremieux could you please review

Adding metrics for McQuaC
