psi-ms.obo

Update the LTQ Orbitrap Elite to clarify that it is sometimes referred to as "Orbitrap Elite". Add the LTQ Orbitrap Velos Pro, acknowledging that it is often just called the Orbitrap Velos Pro (even by Thermo itself). But apparently the original name at release is LTQ Orbitrap Velos Pro

Add Velos Pro

---

psi-ms.obo

This PR includes a set of scores for MaxQuant-DIA experiments. In addition, we added a NIST msp reference to spectra

MaxQuant scores added 

---

psi-ms.obo

Closes #66 
This adds a term for the particular Shimadzu instrument. I don't  see any other Shimadzu GC-MS instruments in the CV though.

Add Shimadzu GCMS-QP2010SE

---

psi-ms.obo

Hi all,
this PR adds PTX-QC as analysis software (to enable referencing itself when writing mzQC files).
I also added https://github.com/HUPO-PSI/psi-ms-CV/commit/5accf6c2de9364a5a1bd3b905b4e48c5651808ae, because OBO-Edit software would not allow me to save the obo file, because:
```
1 fatal error:
PTMProphet normalized information content (MS:1003149) generated 1 error:
 Definition of MS:1003149 cannot contain extended characters.
```
which apparently points to the hyphen `–`, which is (according to OBOEdit) not allowed.
I can revert that part though if desired.

add PTX-QC as software

---

psi-ms.obo
scripts/add_type_relationship.py

Implements the same concept as #50 formally across the entire controlled vocabulary.
I also added three formal data type terms:
```
[Term]
id: MS:1002709
name: compound data type
def: "A data type representing more than a single value." []
[Term]
id: MS:1002710
name: list of type
def: "A data type defining a list of values of a single type." []
is_a: MS:1002709 ! compound data type
[Term]
id: MS:1002711
name: list of strings
def: "A list of xsd:string." []
is_a: MS:1002710 ! list of type
relationship: has_value_type: xsd\:string
[Term]
id: MS:1002712
name: list of integers
def: "A list of xsd:integer." []
is_a: MS:1002710 ! list of type
relationship: has_value_type: xsd\:integer
[Term]
id: MS:1002713
name: list of floats
def: "A list of xsd:float." []
is_a: MS:1002710 ! list of type …
```

Add has_value_type

---

psi-ms.obo
scripts/find_next_available_number.py

This PR covers the first set of terms introduced from the weekly mzSpecLib call. Most terms are specific to mzSpecLib, but `MS:1003167` in particular introduces a term for ProForma2 sequences and may be of interest in other venues.

First Batch of mzSpecLib CV Terms

---

psi-ms.obo

@edeutsch is right that the robot convert step is already changing the OBO imports to OWL.

Switch to PURL for OBO imports

---

psi-ms.obo

As per #105, remove the full NCIT import and just re-declare the 4 NCIT terms that are used in mzQC.
I've used abridged terms from NCIT now that contain the relevant information, without some of the unnecessary `property_value` specifications. I'm not sure though whether the `is_a` specifications might be problematic now, because they refer to NCIT parent terms that are not included in our CV? It shouldn't be our goal to redefine the NCIT tree up to those terms, so if this is indeed problematic, what would be the solution? Have the terms consist of just `id`-`name`-`def`?

Add NCIT terms for mzQC

---

psi-ms.obo

resolves https://github.com/HUPO-PSI/psi-ms-CV/issues/116

adding peptide and spectrum identification count terms

---

psi-ms.obo

This PR adds QC metrics for 'set-use' (involving more than one MS run), with PCA of XIC/MS1-features/precursor-intensities and/or MaxQuant analysis results

adding QC terms for PCA

---

psi-ms.obo

RE @chambm's comment on #130, this PR removes the colon escape from `xsd:` type declarations in relationships

Remove colon escape from relationship, not syntactically necessary

---

psi-ms.obo

This PR adds the peak annotation terms discussed last Friday.
It also includes a few extras encountered during debugging:
1. We had not created CV terms for "other attribute name" and "other attribute value" for user-defined terms in mzSpecLib
2. The "scan number" term had no value-type definition
3. Several of the mass error related terms had "parts per notation" units, but not "parts per million" units

Peak Annotation Terms Plus Extras

---

psi-ms.obo

Closes #142
This PR adds the requested changes to the regular expression for parsing cross linking scores in mzIdentML, and updates the expected domain for those terms bound to the regular expression to permit negative values.
@colin-combe if you could, please check that this matches your intent with the request?

Update cross linking score regular expression and domain

---

psi-ms.obo

Adds the three new peak attribute terms describing how consistent a peak is, and makes the three scalar ion mobility terms peak attributes in addition to their other types.

Peak attribute terms for mzSpecLib

---

psi-ms.obo

TSF is Bruker's replacement for the BAF format. It uses the same SDK as the TDF Format but has no ion mobility dimension. Each frame is a single scan, so we could make the nativeId `scan=`, but in the TSF schema it's called a frame.

Add Bruker TSF format

---

psi-ms.obo

This PR introduces descriptive statistic metrics terms. Some (though not all of the included) items can already be represented with existing terms, this however an alternative/more condensed and flexible representation version of metrics.
Each distribution is represented by a term for the quartiles, for the standard deviation, the mean, and 'outliers' below or above 1.5*IQR. 
Adds terms for:
* peak densities
* S/N
* ion-collection times

distribution representation for various idfree metrics

---

psi-ms.obo

Discussion last year that @dtabb73 initiated suggested that the neutral mass array type is insufficient to describe the range of data types for top-down MS. Sometimes we may want to talk about monoisotopic mass, while in other scenarios we may want to describe the most abundant isotope's mass and there was no way to express this.
Alternatives:
Different units?
```xml
<binaryDataArray>
<cvParam accession="MS:1000514" cvRef="PSI-MS" name="m/z array" unitAccession="MS:1000???" unitCvRef="PSI-MS" unitName="monoisotopic m/z" value=""/>
...
</binaryDataArray>  
```
Extra CV term?
```xml
<binaryDataArray>
<cvParam accession="MS:1000???" cvRef="PSI-MS" name="most abundant m/z summarization" />
<cvParam accession="MS:1000514" cvRef="PSI-MS" name="m/z array" unitAccession="MS:1000040" …
```

Add specific mass array types for top-down MS encoding

---

psi-ms.obo

Adds a new set of terms for expressing that a particular file conforming to a specification requires a specific extension document also be supported in order to be read properly.
This is in support of the extension documents under revision for mzIdentML.

Add extension document versioning

---

psi-ms.obo

This PR adds terms for the Bioconductor software packages [Spectra](https://bioconductor.org/packages/Spectra), [CompoundDb](https://bioconductor.org/packages/CompoundDb) and [MetaboAnnotation](https://bioconductor.org/packages/MetaboAnnotation).

Add Bioconductor packages Spectra, CompoundDb and MetaboAnnotation

---

psi-ms.obo

Hello,
this PR adds and harmonizes interpretation aids for newly added MS terms (see PR #206) and/or aligns the format of existing ones. 
Specifically, this PR
- adds interpretation for the terms MS:4000053-MS:4000060, MS:4000063, MS:4000069, MS:4000070, MS:4000097-MS:4000101, MS:4000152-MS:4000176,
- moves the interpretation from the `def` to the `comment` section. The interpretation is not part of the definition and the interpretation aid should be added as a comment. 
- aligns and harmonizes the wording/formulation with previously existing interpretation.

PR: add and harmonize interpretation aids to obo file for new MS terms 

---

psi-ms.obo

Add 3 instruments and deconvoluted data

---

psi-ms.obo

@mwalzer 
@nilshoffmann
@bittremieux 
please have a look. Thanks! :)
I used the MS:4....... space, since its QC software.
Was also wondering if we should have a new term like
```
[Term]
id: MS:?????
name: quality control software
def: "Quality Control software." [PSI:MS]
is_a: MS:1000531 ! software
```
which we can derive from.

Add first batch of mzqc readers/writers

---

psi-ms.obo

As discussed on PSI call, we want to allow CCS to be encoded in mzML wherever individual ion mobility values are currently allowed.

Add ion mobility attribute as parent for CCS

---

psi-ms.obo

Fixes https://github.com/EBISPOT/ols4/issues/600
Ideally, in a future PR, you should consider to import RO rather than copy pasting the semantics here (i.e. transitivity).

Map MS partof to RO

---

psi-ms.obo

Note: new version assumes that https://github.com/HUPO-PSI/psi-ms-CV/pull/245 is merged first.

Protein contaminant ratio

---

psi-ms.obo

fixes  #241
I've opted to add a `precision` term, which I'm not sure is needed, but since there is `accuracy` already, I thought there is no harm.
However, those two terms are rather narrow, but maybe that's ok. I used a free ID slot (MS:1000394).
We can also remove the precision annotation if desired. I have no strong opinion, but I think may add some helpful context.

add precursor ppm accuracy and precision

---

.github/workflows/trigger-deploy.yml
.github/workflows/update-owl.yaml
psi-ms.obo

OLS has removed the PSI-MS because the owl file is incompatible with OLS4. Until the file is well generated and tested with the OLS4 team please keep the previous version even if it has errors rendering.

Revert owl

---

psi-ms.obo

- Be more precise that it's a ratio rather than a general fraction.
- Add the ratio unit.

Clarify protein contaminants term

---

psi-ms.obo

This restores the references to `STATO` removed in #296 without actually importing it.
It appears to work by just adding nodes for these classes' IDs, but provides zero definition for them, so it would not know about parents or other higher order relations depending upon the `STATO` terms, but still be able to say "these are sample means and these are quantiles"
@bittremieux are these sufficient for MzQC's validator?

Restore deleted STATO references to evaluate validation without import

---

psi-ms.obo

This metric can be computed for MS2 as well as MS1 spectra, so make the categorization a bit more general.

spectra half-TIC for any MS level

---

psi-ms.obo

Add counts units to terms that are part of the MS1XXXXX namespace but can be used as QC-related terms as well. This is necessary for compliant mzQC files and semantic validation.

Add counts units

---

psi-ms.obo

This is required for a DIA-NN converted spectral library to be valid.

Add "is_a: MS:1003207 ! library creation software" to DIA-NN

---

psi-ms.obo
scripts/find_next_available_number.py

Enhances `scripts/find_next_available_number.py` to report the gap size and also now detects an unsorted CV (which would cause reporting of false positive gaps).
e.g.
```
Found gap of size 62: ('MS', 1000938) to ('MS', 1000999)
...
Found gap of size 1: ('MS', 1003236) to ('MS', 1003236)
Found gap of size 2: ('MS', 1003407) to ('MS', 1003408)               <-- false positive...
Found gap of size 2996587: ('MS', 1003413) to ('MS', 3999999)
Found gap of size 1: ('MS', 4000011) to ('MS', 4000011)
Found gap of size 25: ('MS', 4000025) to ('MS', 4000049)
CV is not sorted! MS:1003407 found after MS:4000181
Found gap of size 1000965: ('PEFF', 1036) to ('PEFF', 1002000)
```
Ordering of accessions is restored as well in this PR (eliminating `CV is not sorted! MS:1003407 found after MS:4000181`). …

Accession order fixes

---

psi-ms.obo

distilled from https://github.com/HUPO-PSI/mzQC/issues/244
(version number assumes #330 to be merged)

new QC metrics covering DIA-NN output

---

psi-ms.obo

This has been proposed by the reviewer of the mzSpecLib manuscript. Do we want to make this change? What implications are there for downstream tools and files?

do we want to add "neutral"?

---

.github/workflows/validate-owl.yaml
psi-ms.obo

This PR add quantms to PSI MS as analysis software.

quantms added

---

psi-ms.obo

Some QC terms that were defined as "quartiles" or "quarters" have now been replaced by more general "quantile" terms.
Fixes [mzQC#259](https://github.com/HUPO-PSI/mzQC/issues/259).

Replace quartile/quarter -> quantile

---

psi-ms.obo

Please see: https://github.com/HUPO-PSI/psi-ms-CV/issues/366 for more details.
I used the script in this repository, `find_next_available_number.py` to find the biggest gap in the identifier space, and picked the next from that gap:
```
Found gap of size 2996566: ('MS', 1003434) to ('MS', 3999999)
```

Addition of "AlphaLP" as a new term - refinements and suggestions welcome
